# Generated by Django 3.1.3 on 2021-01-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_token',
        ),
    ]
